/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "Types/Buffer/ELData.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#ifdef ENERGYLEAF_ESP
#error Regenerate this file with the current version of nanopb generator.
#endif
#endif

#ifdef ENERGYLEAF_ESP
PB_BIND(ELData, ELData, AUTO)
#endif


