name: Enforce Branch Policy

on:
  pull_request:
    branches:
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from development branch
        run: |
          if [ "${{ github.head_ref }}" != "development" ]; then
            echo "Pull requests to master must come from the development branch."
            exit 1
          fi